### ISSUE TITLE
Conflict between visual mode highlighting and syntax highlighting of strings

### ISSUE THREAD

**Issue by robber-m** [justy989/ce#11]
If I go to ce.c somewhere in the middle of the first greeting string and I hit `v` the rest of the string is no longer red.
![synatx-highlight-bug](https://user-images.githubusercontent.com/5382774/32999542-e7272eb4-cd70-11e7-93bb-9d7b7f7c0f63.png)

**Comment by justy989** [comment]
fixed in: f7162a39a738f3d19ea4dc504676c20eb3535178

It was really just some weirdness in the default color scheme I think

**Comment by justy989** [comment]
I realized I was wrong about this fix. Re-opening !

**Comment by justy989** [comment]
Ok, fixed for real this time in a5c850f2deae986494fdf53552f97f5724ccf583 and 28aa291ed2f0b4067591e25ba11b6e1dc795dbe3
