### ISSUE TITLE
ddu on the last line of the file adds an extra line to the end of the file

### ISSUE THREAD

**Issue by robber-m** [justy989/ce#19]

**Comment by justy989** [comment]
fixed in 2dea634c416a605a5774bb9b3556f7a97b97370a

**Comment by justy989** [comment]
After fixing this, I'm unhappy with what I did, and undid the fix, so it's back. Thinking more about what exactly I want to do !

**Comment by justy989** [comment]
ok, re-fixed in 7cd6f3494388b0e420cd3d5ee584bbf2dd18aa43
