### ISSUE TITLE
Cursor gets stuck

### ISSUE THREAD

**Issue by robber-m** [justy989/ce#5]
in ce_layout.c on hash 005077fef324c3b6daa07a80c5dc26b2c3306cd0
```
$ ./ce ce_layout.c
8jcctest<Esc>u.a
```
I end up unable to move my cursor. Right before I hit a, my cursor looked like it was one beyond the end of the line instead of at the end.

**Comment by justy989** [comment]
fixed in a8b9f31cd7c52ed31f7139954626e95657d96591 !
