### ISSUE TITLE
`zb` and `zt` should move the view so that the cursor is all the way at the top or bottom

### ISSUE THREAD

**Issue by robber-m** [justy989/ce#6]
Right now it's a few away

Same with `H` and `L` for moving the cursor.

**Comment by justy989** [comment]
This is something that is configurable view CeConfigOption_t's vertical_scroll_off. I set the default config to use a value of 0 and fixed a scrolling bug that didn't take into account the status bar in: 9325ca85ba66031b114c45091b05e5e070744227
