### ISSUE TITLE
Bug with ci}

### ISSUE THREAD

**Issue by robber-m** [justy989/ce#7]
on line :539 in ce_vim.c [commit hash 005077fef324c3b6daa07a80c5dc26b2c3306cd0] if I do `ci}` it should put the close brace on the same line as the opening brace for the function. It is also putting my cursor in insert mode AFTER the close `}`. It should really be in between the two braces.... 

**There is also an undo bug here**. When I undo it doesn't correctly restore the function

**Comment by justy989** [comment]
fixed in: f8910543ba97798b107b9593ca08fec7fed519bd
