### ISSUE TITLE
i and a should not enter INSERT mode in VISUAL mode

### ISSUE THREAD

**Issue by robber-m** [justy989/ce#8]
Right now if I hit `viw` it is putting me in INSERT mode. What should really happen is that the word under my cursor should be highlighted and I should be in VISUAL mode. The same goes for `a` in VISUAL mode.

in other words
If I hit something like `iw` in visual mode it should expand the selection to encompass the current word I'm on. not enter insert mode.

**Comment by justy989** [comment]
fixed in 2dea634c416a605a5774bb9b3556f7a97b97370a
